#ifndef CYPERSTEREO_H_
#define CYPERSTEREO_H_

#define CYPERSTEREO_NAMESPACE cyperstereo
#define CYPERSTEREO_BEGIN_NAMESPACE namespace CYPERSTEREO_NAMESPACE {
#define CYPERSTEREO_END_NAMESPACE }
#define CYPERSTEREO_USE_NAMESPACE using namespace ::CYPERSTEREO_NAMESPACE;  // NOLINT

#endif  // CYPERSTEREO_H_