<?xml version="1.0"?>
<package format="3">
  <name>gripper_teleop</name>
  <version>0.1.0</version>
  <description>Handheld DM3507 gripper detection + AGX gripper teleop bridge.</description>
  <maintainer email="2470428938@qq.com">cyperstereo_team</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
